### ISSUE TITLE
Sending Cypher

### ISSUE THREAD

**Issue by wkolcz** [johnymontana/neovis.js#1]
Not sure if I  missed it already in there or if this could be a feature request, but it would be nice to be able to pull a subgraph using cypher. I have a multi-tenant application and would love to show them the connections for their account instead of the complete graph.

**Comment by johnymontana** [comment]
Thanks @wkolcz that is definitely on the TODO list.

**Comment by johnymontana** [comment]
This is now supported by specifying `initial_cypher` in the config object or calling `Neovis.renderWithCypher(statement). See the [quickstart example](https://github.com/johnymontana/neovis.js#quickstart-example) for more info.
