### ISSUE TITLE
Sample data to replicate graph as per README

### ISSUE THREAD

**Issue by Analect** [johnymontana/neovis.js#2]
@johnymontana 
This looks like a project with great potential. I expect you haven't had time to focus on this but was wondering if you might be able to add a gist that would allow us to load some data to an empty neo4j and reproduce the graph as per the readme. Thanks.

**Comment by johnymontana** [comment]
Sorry for the delayed response, but I've finally added a [quickstart example](https://github.com/johnymontana/neovis.js#quickstart-example) that shows how to produce the visualization (including data for Neo4j).
